// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmlrxfyrhaobemztoknn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tbHJ4ZnlyaGFvYmVtenRva25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDk1NzMsImV4cCI6MjA2ODg4NTU3M30.sqnoUAngMpFc-15f-cs3cHyhLkhxHfHIxLlWrKhv268";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});